### ISSUE TITLE
CSV Directory does not exist

### ISSUE THREAD

**Issue by olufemioyedepo** [jchavannes/mintreport#1]
Im getting a "CSV Directory does not exist" error message whenever i run **bash fetch-transactions.sh**

**Comment by jchavannes** [comment]
Did you create `config.local.sh` and set `CSVDIR`?

e.g.
```
CSVDIR="~/"
```

**Comment by olufemioyedepo** [comment]
Yes i have config.local.sh
This is what my directory looks like
![mint-bash](https://user-images.githubusercontent.com/19518859/50877551-a42d4180-13d2-11e9-98a8-f3615c14159d.PNG)

**Comment by jchavannes** [comment]
The default `CSVDIR` is `~/` which I don't think works on Windows.  You need to setup `config.local.sh` to use a valid `CSVDIR` (directory for saving CSVs from Mint).

**Comment by olufemioyedepo** [comment]
Thanks Jason, i changed `CSVDIR `from` "~/"` to `"/"` and i'm no longer getting the error. 
but now i'm getting a "Error loggin in" message even though i've updated the `USERNAME `and `PASSWORD `values in `config.sh`

**Comment by jchavannes** [comment]
@olufemioyedepo I haven't tested this in a long time.  My guess is that Mint has updated their login process.

**Comment by olufemioyedepo** [comment]
ok thanks for your time Jason.
